steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
        '--build-arg',
        'API=${_API}',
         '-t',
         'gcr.io/glass-guide-286702/companyhub:latest',
         '-t',
         'gcr.io/glass-guide-286702/companyhub:$SHORT_SHA', '-f',
        'Dockerfile.dev', '.']

- name: 'docker'
  args: ['run', '-d', '--name', 'companyhubfrontend', '-t',
        'gcr.io/glass-guide-286702/companyhub:latest']

- name: 'docker'
  args: ['exec', 'companyhubfrontend', 'npm', 'start']

