steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
        '--build-arg',
        'API=${_API}',
         '-t',
         'gcr.io/$PROJECT_ID/companyhub:latest',
         '-t',
         'gcr.io/$PROJECT_ID/companyhub:$SHORT_SHA', '.']

- name: 'docker'
  args: ['run', '-d', '--name', 'companyhubfrontend', '-t',
        'gcr.io/$PROJECT_ID/companyhub:latest']

- name: 'docker'
  args: ['exec', 'companyhubfrontend', 'npm', 'test', '--', '--watchAll=false', '--env=jest-environment-jsdom-sixteen']


- name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/companyhub:latest']

- name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/companyhub:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run',
         'deploy',
         'chfrontend',
        '--image',
        'gcr.io/$PROJECT_ID/companyhub:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed']
