steps:
- name: 'gcr/cloud-builders/docker'
args: ['build', '-t', 'gcr.io/fodase/companyhub:latest',
        't', 'gcr.io/fodase/companyhub:$SHORT_SHA', '.']

- name: 'docker'
  args: ['run', '-d', '--name', 'companyhubfrontend', '-t',
        'gcr.io/fodase/companyhub:latest']

- name: 'docker'
  args: ['push', 'gcr.io/fodase/companyhub:latest']

- name: 'docker'
  args: ['push', 'gcr.io/fodase/companyhub:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run',
         'deploy',
        '--image',
        'gcr.io/fodase/companyhub:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed']
