steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
        '--build-arg',
        'API=${_API}',
        '-t',
        'gcr.io/$PROJECT_ID/frontend:latest',
        '-t',
        'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA', '.']

- name: 'docker'
  args: ['run', '-d', '--name', 'companyhubfrontend', '-t',
        'gcr.io/$PROJECT_ID/frontend:latest']

- name: 'docker'
  args: ['exec', 'companyhubfrontend', 'npm', 'test', '--', '--watchAll=false', '--env=jest-environment-jsdom-sixteen']

- name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:latest']

- name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment',
    'companyhubfrontend',
    'companyhubfrontend=gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=chbackend'

