apiVersion: v1
kind: Service
metadata:
    name: companyhub-service
    labels:
      app: companyhubfrontend
spec:
    type: LoadBalancer #GENERATED AN IP TO CONNECT WITH THE POD ABOVE
    ports:
        - protocol: TCP
          name: http-svc
          port: 80
          targetPort: 8080
    selector:
        app: companyhubfrontend #CONNECT WITH POD ABOVE
